[global]
keyboard = "jp"
country = "jp"
fqdn = "pve1.biwako.internal"
mailto = "admin@usbharu.dev"
timezone = "Asia/Tokyo"
root_password = "password"
# root_ssh_keys = [
#     "ssh-ed25519 AAAA..."
# ]

[network]
source = "from-answer"
cidr = "192.168.10.2/24"
dns = "192.168.10.1"
gateway = "192.168.10.1"

# NICが複数ある場合、どのNICかを選択するためフィルタをかける必要がある
# filter.ID_NET_NAME_MAC = "*e43d1afa379a"
filter.ID_NET_NAME = "enp2s0"

[disk-setup]
filesystem = "ext4"
disk_list = ['nvme0n1']