loki-stack:
  loki:
    url: http://kube-prometheus-stack-loki.monitoring.svc.cluster.local:3100
    isDefault: false
  promtail:
    enabled: true
    config:
      logLevel: info
      serverPort: 3101
      clients:
        - url: http://kube-prometheus-stack-loki.monitoring.svc.cluster.local:3100/loki/api/v1/push