cloudflare-tunnel-ingress-controller:
  cloudflare:
    secretRef:
      name: "cloudflare-external-secret"
      accountIDKey: accountId
      tunnelNameKey: tunnelName
      apiTokenKey: apiToken
  cloudflaredServiceMonitor:
    create: true
  replicaCount: 3
  protocol: http2