apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.argocd.namespace }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: {{ .Values.argocd.namespace }}
spec:
  project: default
  source:
    repoURL: {{ .Values.argocd.repositoryUrl }}
    path: root
    targetRevision: main
    helm:
      releaseName: release
      version: v3
      valueFiles:
      - values.yaml
      parameters:
      - name: argocd.repositoryUrl
        value: {{ .Values.argocd.repositoryUrl }}
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .Values.argocd.namespace }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true