apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  project: default
  source:
    repoURL: {{ .Values.argocd.repositoryUrl }}
    path: root
    targetRevision: master
    helm:
      releaseName: release
      version: v3
      valueFiles:
      - values.yaml
      parameters:
      - name: argocd.repositoryUrl
        value: {{ .Values.argocd.repositoryUrl }}
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true