apiVersion: v1
kind: Secret
metadata:
  name: backup-cron-job-secret
  namespace: misskey
type: Opaque
data:
  AWS_ACCESS_KEY_ID: {{ .Values.secret.cloudflare.r2.accessKey }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.secret.cloudflare.r2.accessSecretKey }}
  AWS_DEFAULT_REGION: "YXV0bw=="
  S3_ENDPOINT: {{ .Values.secret.cloudflare.r2.endpoint }}
