apiVersion: v1
kind: Secret
metadata:
  name: misskey-backup-cred
type: Opaque
data:
  ACCESS_KEY_ID: {{ .Values.secret.cloudflare.r2.accessKey }}
  ACCESS_SECRET_KEY: {{ .Values.secret.cloudflare.r2.accessSecretKey }}
  REGION: "YXV0bw=="


#WARNING: You should not place the username and password in the version control repository or anywhere else in plain text.
#Instead, use the Services Tool Window -> Kubernetes -> <Desired Cluster> -> Configuration -> <right-click on Secrets> -> Create New Secret...
