apiVersion: v1
kind: Namespace
metadata:
  name: cloudflare-tunnel
---
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-external-secret
  namespace: cloudflare-tunnel
type: Opaque
stringData:
  accountId: "{{ .Values.secret.cloudflare.accountId }}"
  apiToken: "{{ .Values.secret.cloudflare.tunnel.apiToken }}"
  tunnelName: "usbharu-lab-cloudflare-tunnel"
---
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-external-secret
  namespace: cert-manager
type: Opaque
data:
  apiToken: {{ .Values.secret.cloudflare.tunnel.apiToken }}