apiVersion: v1
data:
  cluster: {{ .Values.secret.grafanaCloud.cluster }}
  hosted-grafana-id: {{ .Values.secret.grafanaCloud.hostedGrafanaId }}
  token: {{ .Values.secret.grafanaCloud.token }}
kind: Secret
metadata:
  name: grafana-pdc-agent
  namespace: pdc-agent