apiVersion: v1
kind: Secret
metadata:
  name: now-playing-secret
  namespace: nowplaying
type: Opaque
stringData:
  SPOTIFY_ACCESS_TOKEN: "{{ .Values.secret.nowplaying.spotify.accessToken }}"
  SPOTIFY_REFRESH_TOKEN: "{{ .Values.secret.nowplaying.spotify.refreshToken }}"
  SPOTIFY_CLIENT_ID: "{{ .Values.secret.nowplaying.spotify.clientId }}"
  SPOTIFY_CLIENT_SECRET: "{{.Values.secret.nowplaying.spotify.clientSecret}}"
  MISSKEY_ENDPOINT: "{{.Values.secret.nowplaying.misskey.endpoint}}"
  MISSKEY_TOKEN: "{{.Values.secret.nowplaying.misskey.token}}"

#WARNING: You should not place the username and password in the version control repository or anywhere else in plain text.
#Instead, use the Services Tool Window -> Kubernetes -> <Desired Cluster> -> Configuration -> <right-click on Secrets> -> Create New Secret...
