apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
spec:
  project: default
  source:
    repoURL: {{ .Values.argocd.repositoryUrl }}
    path: applications/monitoring
    targetRevision: master
    helm:
      releaseName: kube-prometheus-stack
      version: v3
      valueFiles:
        - values.yaml
      parameters:
        - name: kube-prometheus-stack.alertmanager.config.receivers[0].discord_configs[0].webhook_url
          value: {{ .Values.monitoring.webhookUrl }}
        - name: kube-prometheus-stack.grafana.adminPassword
          value: {{ .Values.monitoring.grafanaPassword }}
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .Values.monitoring.namespace }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true