apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nowplaying
  namespace: argocd
spec:
  project: default
  source:
    repoURL: {{ .Values.argocd.repositoryUrl }}
    path: applications/nowplaying
    targetRevision: master
    helm:
      releaseName: release
      version: v3
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: nowplaying
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true