apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.postgresql.namespace }}
  namespace: postgresql
spec:
  project: default
  source:
    repoURL: {{ .Values.argocd.repositoryUrl }}
    path: applications/postgresql
    targetRevision: main
    helm:
      releaseName: release
      version: v3
      valueFiles:
      - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .Values.postgresql.namespace }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
