apiVersion: v2
name: traefik
description: Traefik

type: application

version: 0.1.0

appVersion: "1.16.0"
dependencies:
- name: "traefik"
  repository: https://traefik.github.io/charts
  version: "36.0.0"
