traefik:
  metrics:
    prometheus:
      service:
        enabled: true
      serviceMonitor:
        enabled: true
      prometheusRule:
        enabled: true
  ingressRoute:
    dashboard:
      enabled: true