apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-cloudflare-warp-proxy-service
spec:
  selector:
    app: {{ .Release.Name }}-cloudflare-warp-proxy
  ports:
    - protocol: TCP
      port: 40000
  