apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: "{{ .Release.Name }}-misskey-cluster"
  annotations:
    argocd.argoproj.io/sync-options: Delete=false
spec:
  enableSuperuserAccess: true
  instances: 3
  storage:
    size: 10Gi
    storageClass: nfs-csi-fast
  monitoring:
    enablePodMonitor: true
  bootstrap:
    initdb:
      database: misskey
      owner: misskey
  postgresql:
    parameters:
      max_connections: "300"
      shared_buffers: "1GB"
      effective_cache_size: "3GB"
      maintenance_work_mem: "256MB"
      checkpoint_completion_target: "0.9"
      wal_buffers: "16MB"
      default_statistics_target: "100"
      random_page_cost: "4"
      effective_io_concurrency: "2"
      work_mem: "1747kB"
      huge_pages: "off"
      min_wal_size: "2GB"
      max_wal_size: "8GB"
  resources:
    requests:
      memory: "1Gi"
      cpu: "200m"
    limits:
      memory: "4Gi"
      cpu: "1"
  managed:
    services:
      disabledDefaultServices: [ "ro", "r" ]
      additional:
        - selectorType: rw
          serviceTemplate:
            metadata:
              name: "{{ .Release.Name }}-misskey-cluster-rw-np"
            spec:
              type: NodePort
              ports:
                - name: postgres
                  port: 5432
                  targetPort: 5432
                  protocol: TCP
          updateStrategy: patch