apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: "{{ .Release.Name }}-misskey-cluster"
spec:
  logLevel: debug
  enableSuperuserAccess: true
  instances: 3
  storage:
    size: 10Gi
  monitoring:
    enablePodMonitor: true
  bootstrap:
    initdb:
      database: misskey
      owner: misskey
  backup:
    barmanObjectStore:
      destinationPath: "s3://{{ .Values.database.backup.bucketName }}"
      endpointURL: {{ .Values.database.backup.endpointUrl }}
      wal:
        compression: gzip
        encryption: AES256
      s3Credentials:
        accessKeyId:
          name: "misskey-backup-cred"
          key: "ACCESS_KEY_ID"
        secretAccessKey:
          name: "misskey-backup-cred"
          key: "ACCESS_SECRET_KEY"
        region:
          key: "REGION"
          name: "misskey-backup-cred"