apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-misskey-config
data:
  default.yml: |-
    url: {{ .Values.misskey.url }}
    port: {{ .Values.misskey.port }}

    db:
      host: {{ .Release.Name }}-misskey-cluster-rw
      port: 5432
      db: misskey
      user: misskey

    dbReplications: false

    redis:
      host: {{ .Release.Name }}-redis-service
      port: 6379

    id: {{ .Values.misskey.id }}
    signToActivityPubGet: true