apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-misskey
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-misskey
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/ConfigMap.yaml") . | sha256sum }}
      labels:
        app: {{ .Release.Name }}-misskey
    spec:
      containers:
        - name: {{ .Release.Name }}-misskey-server-container
          image: {{ .Values.misskey.image }}
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: "0.5"
              memory: "2Gi"
            limits:
              cpu: "2"
              memory: "4Gi"
          command: [ "pnpm", "run", "migrateandstart" ]
          env:
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-misskey-cluster-app
                  key: password
          volumeMounts:
            - name: misskey-default-yaml-config
              mountPath: /misskey/.config
          livenessProbe:
            initialDelaySeconds: 10
            periodSeconds: 10
            exec:
              command:
                - curl
                - -X POST
                - -f
                - -k
                - '-H "Content-Type: application/json"'
                - '-d "{}"'
                - {{ .Values.misskey.url }}/api/ping
          readinessProbe:
            initialDelaySeconds: 10
            periodSeconds: 10
            exec:
              command:
                - curl
                - -X POST
                - -f
                - -k
                - '-H "Content-Type: application/json"'
                - '-d "{}"'
                - {{ .Values.misskey.url }}/api/ping
      volumes:
        - name: misskey-default-yaml-config
          configMap:
            name: {{ .Release.Name }}-misskey-config