apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-misskey
spec:
  replicas: {{ .Values.maintenance.misskeyReplica }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-misskey
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/ConfigMap.yaml") . | sha256sum }}
      labels:
        app: {{ .Release.Name }}-misskey
    spec:
      initContainers:
        - name: {{ .Release.Name }}-db-migrate
          image: {{ .Values.misskey.image }}
          command: [ "pnpm", "run", "migrate" ]
          env:
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-misskey-cluster-app
                  key: password
          volumeMounts:
            - name: misskey-default-yaml-config
              mountPath: /misskey/.config
      containers:
        - name: {{ .Release.Name }}-misskey-server-container
          image: {{ .Values.misskey.image }}
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: {{ .Values.misskey.resources.requests.cpu }}
              memory: {{ .Values.misskey.resources.requests.memory }}
            limits:
              cpu: {{ .Values.misskey.resources.limits.cpu }}
              memory: {{ .Values.misskey.resources.limits.memory }}
          command: [ "pnpm", "run", "migrateandstart" ]
          env:
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-misskey-cluster-app
                  key: password
          volumeMounts:
            - name: misskey-default-yaml-config
              mountPath: /misskey/.config
          livenessProbe:
            periodSeconds: 10
            exec:
              command:
                - curl
                - -X
                - POST
                - -f
                - -k
                - -H
                - "Content-Type: application/json"
                - -d
                - '{}'
                - http://localhost:3000/api/ping
          readinessProbe:
            periodSeconds: 10
            exec:
              command:
                - curl
                - -X
                - POST
                - -f
                - -k
                - -H
                - "Content-Type: application/json"
                - -d
                - '{}'
                - http://localhost:3000/api/ping
          startupProbe:
            failureThreshold: 30
            periodSeconds: 1000
            exec:
              command:
                - curl
                - -X
                - POST
                - -f
                - -k
                - -H
                - "Content-Type: application/json"
                - -d
                - '{}'
                - http://localhost:3000/api/ping
      volumes:
        - name: misskey-default-yaml-config
          configMap:
            name: {{ .Release.Name }}-misskey-config