{{/*apiVersion: networking.k8s.io/v1*/}}
{{/*kind: Ingress*/}}
{{/*metadata:*/}}
{{/*  name: {{ .Release.Name }}-misskey*/}}
{{/*spec:*/}}
{{/*  ingressClassName: cloudflare-tunnel*/}}
{{/*  rules:*/}}
{{/*    - host: {{ .Values.ingress.host }}*/}}
{{/*      http:*/}}
{{/*        paths:*/}}
{{/*          {{ if .Values.maintenance.enable }}*/}}
{{/*          - path: /*/}}
{{/*            pathType: Prefix*/}}
{{/*            backend:*/}}
{{/*              service:*/}}
{{/*                name: {{ .Release.Name }}-misskey-sorry-page-service*/}}
{{/*                port:*/}}
{{/*                  number: 3000*/}}
{{/*          {{ else }}*/}}
{{/*          - path: /*/}}
{{/*            pathType: Prefix*/}}
{{/*            backend:*/}}
{{/*              service:*/}}
{{/*                name: {{ .Release.Name }}-misskey-service*/}}
{{/*                port:*/}}
{{/*                  number: 3000*/}}
{{/*          {{ end }}*/}}