apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Release.Name }}-misskey-exporter-service-monitor
spec:
  endpoints:
    - port: "metrics"
      path: /metrics
  namespaceSelector:
    matchNames:
      - misskey
  selector:
    matchLabels:
      usbharu.dev/misskey-service: {{ .Release.Name }}-misskey-service