apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-misskey-exporter-service
spec:
  selector:
    app: {{ .Release.Name }}-misskey-exporter
  ports:
    - name: metrics
      protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
  