kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-{{ .Release.Name }}-misskey-redis
  annotations:
    argocd.argoproj.io/sync-options: Delete=false
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: nfs-csi-fast
  resources:
    requests:
      storage: 3Gi