apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-redis
  labels:
    app: {{ .Release.Name }}-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-redis
  template:
    metadata:
      name: {{ .Release.Name }}-redis
      labels:
        app: {{ .Release.Name }}-redis
    spec:
      containers:
        - name: redis
          image: redis:7
          volumeMounts:
            - mountPath: /data
              name: redis-volume
          resources:
            limits:
              memory: {{ .Values.redis.resources.limits.memory }}
              cpu: {{ .Values.redis.resources.limits.cpu }}
            requests:
              memory: {{ .Values.redis.resources.requests.memory }}
              cpu: {{ .Values.redis.resources.requests.cpu }}
          ports:
            - containerPort: 6379
      restartPolicy: Always
      volumes:
        - name: redis-volume
          persistentVolumeClaim:
            claimName: pvc-{{ .Release.Name }}-misskey-redis
      