apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-misskey-service
  labels:
    usbharu.dev/misskey-service: {{ .Release.Name }}-misskey-service
spec:
  selector:
    app: {{ .Release.Name }}-misskey
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP