apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: staging-letsencrypt-issuer
spec:
  acme:
    email: {{ .Values.letsencrypt.email }}
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: acme-client-staging-letsencrypt
    solvers:
      - http01:
          ingress:
            class: cloudflare-tunnel