apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: staging-letsencrypt-issuer
spec:
  acme:
    email: {{ .Values.letsencrypt.email }}
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: acme-client-staging-letsencrypt
    solvers:
      - dns01:
          cloudflare:
            apiTokenSecretRef:
              name: cloudflare-external-secret
              key: apiToken