apiVersion: v2
name: monitoring
description: Monitoring Chart of usbharu-lab

type: application

version: 0.1.0
appVersion: "1.16.0"
dependencies:
- name: kube-prometheus-stack
  repository: https://prometheus-community.github.io/helm-charts
  version: "72.6.3"
