kube-prometheus-stack:
  prometheus-node-exporter:
    hostRootFsMount:
      enabled: false
  prometheus:
    prometheusSpec:
      podMonitorSelectorNilUsesHelmValues: false
      probeSelectorNilUsesHelmValues: false
      ruleSelectorNilUsesHelmValues: false
      serviceMonitorSelectorNilUsesHelmValues: false
      logLevel: info

ingress:
  annotations:
  hosts: "grafana.lab.usbharu.dev.internal"
  tls:
  - hosts:
    - "grafana.lab.usbharu.dev.internal"
    secretName: grafana-selfsigning-cert
service:
  externalPort: 80
