ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: "selfsigning-issuer"
  hosts:
  - "grafana.lab.usbharu.dev.internal"
  tls:
  - hosts:
    - "grafana.lab.usbharu.dev.internal"
    secretName: grafana-selfsigning-cert
service:
  externalPort: 80

kube-prometheus-stack:
  prometheus-node-exporter:
    hostRootFsMount:
      enabled: false
  prometheus:
    prometheusSpec:
      podMonitorSelectorNilUsesHelmValues: false
      probeSelectorNilUsesHelmValues: false
      ruleSelectorNilUsesHelmValues: false
      serviceMonitorSelectorNilUsesHelmValues: false
      logLevel: info
  alertmanager:
    enabled: true
    config:
      replicas: 2
      route:
        receiver: "discord-webhook"
        routes:
          - receiver: "discord-webhook"
        receivers:
          - name: "discord-webhook"
            webhook_configs:
              - url: "https://example.com"
                send_resolved: true
