ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: "selfsigning-issuer"
  hosts:
  - "grafana.lab.usbharu.dev.internal"
  tls:
  - hosts:
    - "grafana.lab.usbharu.dev.internal"
    secretName: grafana-selfsigning-cert
service:
  externalPort: 80

kube-prometheus-stack:
  prometheus-node-exporter:
    hostRootFsMount:
      enabled: false
  prometheus:
    prometheusSpec:
      podMonitorSelectorNilUsesHelmValues: false
      probeSelectorNilUsesHelmValues: false
      ruleSelectorNilUsesHelmValues: false
      serviceMonitorSelectorNilUsesHelmValues: false
      logLevel: info

  alertmanager:
    alertmanagerSpec:
      replicas: 2
    enabled: true
    config:
      route:
        receiver: "discord-webhook"
        routes:
          - receiver: "discord-webhook"
      receivers:
        - name: "discord-webhook"
          discord_configs:
#          webhook_configs:
            - webhook_url: "https://example.com"
              send_resolved: true
