apiVersion: v2
name: monitor
description: A Helm chart for Kubernetes

type: application

version: 0.1.0

appVersion: "1.16.0"
dependencies:
- name: "cloudnative-pg"
  repository: https://cloudnative-pg.github.io/charts
  version: "0.26.0"
