apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-mongodb-service
spec:
  selector:
    app.kubernetes.io/instance: {{ .Release.Name }}-mongodb
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
      name: mongodb
  type: NodePort
  