apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-mvs-minio-public
spec:
  ingressClassName: cloudflare-tunnel
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-minio
                port:
                  number: 9000
      host: "{{ .Release.Name }}-minio-mvs.usbharu.dev"