apiVersion: apps/v1
kind: Deployment
metadata:
  name: now-playing
  labels:
    app: now-playing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: now-playing
  template:
    metadata:
      name: now-playing
      labels:
        app: now-playing
    spec:
      containers:
        - name: now-playing
          image: git.usbharu.dev/usbharu/now-playing:a6fc757
          imagePullPolicy: IfNotPresent
          envFrom:
            - secretRef:
                name: "now-playing-secret"
      restartPolicy: Always
      