apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-csi-fast
provisioner: nfs.csi.k8s.io

parameters:
  server: 192.168.10.2
  share: /var/k8s/nfs
reclaimPolicy: Delete
volumeBindingMode: Immediate
mountOptions:
  - nfsvers=4.1
