misskey:
  url: "https://misskey.usbharu.dev"
  port: 3000
  id: "aid"

ingress:
  host: "staging-misskey.usbharu.dev"
  issuer: staging-letsencrypt-issuer

database:
  backup:
    bucketName: misskey-backup
    endpointUrl: "https://76906b4e38909e314e89939ec9f8e485.r2.cloudflarestorage.com/misskey-backup"