misskey:
  url: "https://misskey.usbharu.dev"
  port: 3000
  id: "aid"
  proxy: "http://release-cloudflare-warp-proxy-service.proxy:40000"
  image: misskey/misskey:2024.11.0
  clusterLimit: 1
  deliverJobConcurrency: 128
  inboxJobConcurrency: 16
  relationshipJobConcurrency: 16
  deliverJobPerSec: 128
  inboxJobPerSec: 32
  relationshipJobPerSec: 64
  deliverJobMaxAttempts: 12
  inboxJobMaxAttempts: 8

ingress:
  host: "misskey.usbharu.dev"

backup:
  bucketName: misskey-backup
  cron: "0 3 * * 1"

maintenance:
  enable: false
  misskeyReplica: 1