misskey:
  url: "https://misskey.usbharu.dev"
  port: 3000
  id: "aid"
  proxy: "http://release-cloudflare-warp-service.proxy:40000"

ingress:
  host: "misskey.usbharu.dev"

backup:
  bucketName: misskey-backup