misskey:
  url: "https://negi.usbharu.dev"
  port: 3000
  id: "aidx"
  proxy: "http://release-cloudflare-warp-proxy-service.proxy:40000"

ingress:
  host: "negi.usbharu.dev"

backup:
  bucketName: misskey-backup