misskey:
  url: "https://negi.usbharu.dev"
  port: 3000
  id: "aidx"
  proxy: "http://release-cloudflare-warp-proxy-service.proxy:40000"
  image: misskey/misskey:2025.2.0
  clusterLimit: 2
  deliverJobConcurrency: 128
  inboxJobConcurrency: 128
  relationshipJobConcurrency: 128
  deliverJobPerSec: 128
  inboxJobPerSec: 128
  relationshipJobPerSec: 128
  deliverJobMaxAttempts: 12
  inboxJobMaxAttempts: 8

ingress:
  host: "negi.usbharu.dev"

backup:
  bucketName: misskey-backup
  cron: "0 8 * * *"

maintenance:
  enable: true
  misskeyReplica: 0
